### ISSUE TITLE
Informert og ettertrykke samtykke til karussel

### ISSUE THREAD

**Issue by otell** [Frikanalen/frikanalen#101]
Forslag til det som i dag ligger under My video -> edit video, altså der metadata legges inn:
I dagens løsning huker redaktøren av filler-flagget dersom vedkommende godtar at den aktuelle videoen skal kunne legges til i karusselen.
For å forsikre oss om at redaktøren faktisk har samtykket til dette, foreslås følgende tekst:
* Vil du at videoen skal gjøres tilgjengelig for automatisk avspilling? JA / NEI
* Merk at du fortsatt har redaktøransvaret for videoen.
* Når du ikke lenger ønsker at videoen skal kunne avspilles automatisk, må du huske å endre innstillingen.

**Comment by petterreinholdtsen** [comment]
Malen for teksten på My video -> Edit video ligger i fkbeta/templates/agenda/manage_video_new.html, men feltbeskrivelsene kommer fra fk/models.py.

**Comment by petterreinholdtsen** [comment]
Jeg har gjort et forsøk, men trenger tilbakemelding på om det fyller behovet.

**Comment by otell** [comment]
Beklager sent svar. Kan du endre filler-flagget til å vise ovenfor foreslått tekst i stedet?
