### ISSUE TITLE
./manage.py dumpdata fail with 'CommandError: Unable to serialize database: no such table: fkprofile_profile'

### ISSUE THREAD

**Issue by petterreinholdtsen** [Frikanalen/frikanalen#120]
When trying to run the dumpdata command, it starts dumping json content and then stop with this error:
```
CommandError: Unable to serialize database: no such table: fkprofile_profile
```

I have no idea what is wrong.

**Comment by petterreinholdtsen** [comment]
I still have no idea what is wrong, but managed to dump the rest of the data using ```./manage.py dumpdata --exclude fkprofile```.  When looking at the sqlite database using ```sqlite3 fkbeta/default.db .dump | grep fkprofile```, there is no fkprofile_profile table.

**Comment by odinho** [comment]
Any specific reason you are doing this?

**Comment by petterreinholdtsen** [comment]
Yes, to get a complete view on what is in the database.  I started by looking into backing up the old filenames, and ran into this crash bug which seem like a bug somewhere in our models.

**Comment by odinho** [comment]
It's better to do a postgresql dump then:
```
sudo -u postgres pg_dump fkweb > fkweb.sql
```
