### ISSUE TITLE
There are no CORS headers for the Frikanalen API

### ISSUE THREAD

**Issue by toresbe** [Frikanalen/frikanalen#171]
I'm working against the program schedule API and I'm struggling to fetch it to write a CasparCG template for playout. Chrome's console gives me the following error message:

> Access to fetch at 'https://frikanalen.no/api/scheduleitems/?page_size=10000?days=1' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

The basic Googling I've done has shown me that there's this thing, which seems to make it easy to apply CORS headers to django-rest-framework APIs: https://github.com/adamchainz/django-cors-headers

If anyone (cough @odinho) could take a look at that and save me the mental context change from what I'm hacking on now, that'd be great!

**Comment by odinho** [comment]
A bit weird you'd need that, but anyway no problem to put CORS on the API, it might even make some integrations cooler down the line. So sure.

**Comment by odinho** [comment]
Deployed.

**Comment by toresbe** [comment]
Awesome, thanks! I'll be posting another demo video to the mailing list about this.
