### ISSUE TITLE
Make sure front page do not leak information to external servers.

### ISSUE THREAD

**Issue by petterreinholdtsen** [Frikanalen/frikanalen#185]
https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Ffrikanalen.no%2F show how the Frikanalen front page leak information to external servers.  This is similar to the issue resolved in #100.  Please make sure the web site do not leak its users information to external actors like Google.

**Comment by toresbe** [comment]
The worst issue has been resolved, the use of Google CDNs for our fonts. 

I'll set aside some time soon-ish to evaluate the other headers and how they apply to us.

**Comment by toresbe** [comment]
Fix now merged into main. Will explore eg. helmet.js
