### ISSUE TITLE
Recode into ogv

### ISSUE THREAD

**Issue by toresbe** [Frikanalen/frikanalen#44]
System needs to be able to produce ogv files

**Comment by petterreinholdtsen** [comment]
While we wait for such feature, I have added a small shell script taking care of this.

**Comment by petterreinholdtsen** [comment]
The script is on ftp.frikanalen.tv as /tank/pere/fk-member-tools/generate-missing-ogv .

**Comment by petterreinholdtsen** [comment]
As far as I can tell, OGV files are generated automatically after upload.  Closing as fixed.
