### ISSUE TITLE
API documentation is incorrect

### ISSUE THREAD

**Issue by toresbe** [Frikanalen/frikanalen#52]
The REST API documents itself as wanting the "video_id", but throws an error unless you feed it as "video". Since I'm not sure which is right and which is wrong, I'm passing the buck for this in a ticket :)

**Comment by petterreinholdtsen** [comment]
Where did you see video_id, and where did  you see video?  I've seen two kind of video refs, either the ID number or a URL similar to http://beta.frikanalen.tv/api/videos/625326 (from http://beta.frikanalen.tv/api/scheduleitems/ ).

**Comment by petterreinholdtsen** [comment]
Without more information, it is not possible to do anything about this, so I close it.  If you have more information, please reopen.
