### ISSUE TITLE
FTP auth against rest api

### ISSUE THREAD

**Issue by phed** [Frikanalen/frikanalen#54]
Make the FTP authenticate against the rest API - using http basic auth - see #51.

**Comment by petterreinholdtsen** [comment]
Given that FTP always is unencrypted, while the API and web site can be placed behind https to encrypt password transfer, I would suggest to have a separate password for ftp and django/web/api access.

**Comment by Velmont** [comment]
Should maybe change to sftp instead?

**Comment by petterreinholdtsen** [comment]
We should definitely move to a upload method where the password is not sent in clear text, yeah.  sftp or some method where it is possible to resume transfer would be good.

**Comment by petterreinholdtsen** [comment]
The FTP upload is retired.  Closing this issue as no longer relevant.
