### ISSUE TITLE
Link to XMLTV from front page?

### ISSUE THREAD

**Issue by petterreinholdtsen** [Frikanalen/frikanalen#75]
Frikanalen provide its schedule in XMLTV format on http://beta.frikanalen.no/xmltv/YYYY/MM/DD ,
see for example http://beta.frikanalen.no/xmltv/2015/02/04/ .  But this is not possible to see when
visiting beta.frikanalen.no.  Perhaps we should add an XMLTV link next to the REST API and Source Code links below each page?  Or an XMLTV link on the http://beta.frikanalen.tv/guide/ page?  It could
point to a web page explaining how the XMLTV links should be constructed, or directly to the current XMLTV listing.

**Comment by Velmont** [comment]
Fixed.
