### ISSUE TITLE
User country is lost when adding via the user form

### ISSUE THREAD

**Issue by petterreinholdtsen** [Frikanalen/frikanalen#77]
When visiting http://beta.frikanalen.tv/user/ and adding a country to the country field, the value do not
"stick".  I submit the form and the country stay, but when I reload the page the country field is yet again empty.

**Comment by petterreinholdtsen** [comment]
I tested this using https://frikanalen.no/user/, and the country is still not saved.

**Comment by petterreinholdtsen** [comment]
I suspect this is related to #120, as the country is part of the userprofile model.

**Comment by toresbe** [comment]
The user no longer has a country field in the database, so this no longer applies. Closing.
