### ISSUE TITLE
Upgrade to Django REST framework 3.0+

### ISSUE THREAD

**Issue by Velmont** [Frikanalen/frikanalen#79]
We're on 2.x. But 3.x is cooler with a simpler API and some nice rewrites.

**Comment by petterreinholdtsen** [comment]
[Odin Hørthe Omdal]
> We're on 2.x. But 3.x is cooler with a simpler API and some nice
> rewrites.

Which of the API calls we currently have will change, and how?

I would rather not rewrite the tools I already have written. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by Velmont** [comment]
I don't think they'll change because of the framework upgrade. It's the internal API that changes. The API to write the API, so to say :)

**Comment by Velmont** [comment]
Oki, this is now merged. 4e9a5f9..fd34855
