### ISSUE TITLE
Videos created using API are missing the 'Proper import' flag

### ISSUE THREAD

**Issue by petterreinholdtsen** [Frikanalen/frikanalen#82]
When adding video entries using the API, the entry causes a 500 internal server error until the 'proper import' flag is set using the django admin interface.  Please change the API to produce working entries.

**Comment by petterreinholdtsen** [comment]
[Odin Hørthe Omdal]
> Closed #82 via 3bd240895b317052d36a84dcfc7b2ba0510c3859.

When I tested my code using frikanalen-dev.nuug.no, the problem still
exited.  Fresh video entries lack the "Proper import" flag, do not show
up on the list of videos can can not be found using the API search.

--
Happy hacking
Petter Reinholdtsen

**Comment by Velmont** [comment]
I didn't change the default. But you can set proper import yourself now.
Which should be enough to resolve this bug :)

Just send `"proper_import": true` along with your other data. Or change it
when you've uploaded and transcoded everything. I'm not really sure what
proper import is really supposed to mean.

**Comment by petterreinholdtsen** [comment]
[Odin Hørthe Omdal]
> I didn't change the default. But you can set proper import yourself now.
> Which should be enough to resolve this bug :)
>
> Just send `"proper_import": true` along with your other data. Or change it
> when you've uploaded and transcoded everything.

Ah.  Of course.  Fixing.  Given that the API do not find such entries
and the web interface report a internal server error, I prefer to keep
the value as true all the time.

> I'm not really sure what proper import is really supposed to mean.

Me neither, but it is set automatically when creating a new video using
the admin/Django interface, so I suspect the default should be true, not
false.
-- 
Happy hacking
Petter Reinholdtsen
