### ISSUE TITLE
Fix the custom fields to modern Django standard (MillisecondField)

### ISSUE THREAD

**Issue by odinho** [Frikanalen/frikanalen#89]
Getting these deprecation messages.  Must be fixed before we upgrade to Django 1.10 at latest.

```
frikanalen/fkbeta/fk/fields.py:30: RemovedInDjango110Warning: 
    SubfieldBase has been deprecated. Use Field.from_db_value instead.

  class MillisecondField(IntegerField):
```

**Comment by petterreinholdtsen** [comment]
Is this fixed now?  A search for MillisecondField only show it as a class in fk/fields.py, which seem to be unused.

**Comment by odinho** [comment]
Yeah, I actually did upgrade to 1.10 and so fixed that then. But now we've fixed the fix. MillisecondField is there because we used to have a migration depending on it. But now we've removed those, we can remove MillisecondField too. I forgot about that.

**Comment by petterreinholdtsen** [comment]
OK.  I assign it to you then, and hope you find time to do the cleanup.

**Comment by petterreinholdtsen** [comment]
Any hope to have this cleanup done before christmas?  The old duration code is the last part depending in stuff not already in Debian, forcing me to use this patch to test on Debian:

```
--- a/fkbeta/fk/models.py
+++ b/fkbeta/fk/models.py
@@ -16,7 +16,10 @@ from django.utils.timezone import utc
 from django.utils.translation import ugettext as _
 from model_utils import Choices
 from model_utils.models import TimeStampedModel
-from durationfield.db.models.fields.duration import DurationField as LegacyDurationField
+try:
+    from durationfield.db.models.fields.duration import DurationField as LegacyDurationField
+except:
+    from django.db.models import DurationField as LegacyDurationField
 
 """
 Models for the Frikanalen database.
```
